# QuickShop Shop Search AddOn
# Works with both Reremake and Hikari forks of QuickShop

# PLEASE refer the below link to understand the meaning of all the fields and sample data:
# https://gitlab.com/ronsane/QSFindItemAddOn/-/wikis/Sample-config.yml

plugin-prefix: '&c'
find-item-command:
  command-alias:
    - searchshop
    - shopsearch
    - searchitem
  incorrect-usage-message: '&cIncorrect usage! Try /finditem &f{TO-BUY | TO-SELL}
    {item type | item name}'
  invalid-material-message: '&cEither no shops were found or you provided an invalid
    item! Try selecting from autofill.'
  shop-search-loading-message: '&eSearching for shops...'
  no-shop-found-message: '&cNo shops found!'
  find-item-command-no-permission-message: '&cNo permission!'
  to-buy-autocomplete: TO_BUY
  to-sell-autocomplete: TO_SELL
  hideshop-autocomplete: hideshop
  revealshop-autocomplete: revealshop
  shop-hide-success-message: '&aShop is now hidden from search list!'
  shop-reveal-success-message: '&aShop is no longer hidden from search list!'
  shop-already-hidden-message: '&cThis shop is already hidden!'
  shop-already-public-message: '&cThis shop is already public!'
  invalid-shop-block-message: '&cThe block you are looking at is not a shop!'
  hiding-shop-owner-invalid-message: '&cThat shop is not yours!'
shop-sorting-method: 2
search-loaded-shops-only: false
shop-search-gui-title: '&8Available Shops'
nearest-warp-mode: 1
shop-gui-item-lore:
  - ''
  - '&7Price: &a${ITEM_PRICE}'
  - '&7Stock: &f{SHOP_STOCK}'
  - '&7Owner: &f{SHOP_OWNER}'
  - '&7Location: &f{SHOP_LOC}'
  - '&7World: &f{SHOP_WORLD}'
  - '&7Warp: &f{NEAREST_WARP}'
  - '&7Shop Visits: &f{SHOP_VISITS}'
  - ''
player-shop-teleportation:
  direct-shop-tp-mode:
    tp-player-directly-to-shop: true
    click-to-teleport-message: '&a» Click to teleport to the shop!'
    shop-tp-no-permission-message: '&c» You don''t have permission to teleport to
      shop!'
    unsafe-shop-area-message: '&c» The area around the shop is unsafe!'
    tp-delay-in-seconds: 0
    tp-delay-message: '&a» You will be teleported in &f{DELAY} seconds&a...'
  nearest-warp-tp-mode:
    tp-player-to-nearest-warp: false
shop-gui-back-button-material: ''
shop-gui-back-button-text: '&c« &c&lBack'
shop-gui-next-button-material: ''
shop-gui-next-button-text: '&a&lNext&a »'
shop-gui-filler-item: GRAY_STAINED_GLASS_PANE
shop-gui-close-button-material: REDSTONE
shop-gui-close-button-text: '&c&lClose Search'
shop-gui-back-button-custom-model-data: ''
shop-gui-next-button-custom-model-data: ''
shop-gui-close-button-custom-model-data: ''
shop-navigation-first-page-alert-message: '&cYou are already on first page!'
shop-navigation-last-page-alert-message: '&cYou are already on last page!'
shop-player-visit-cooldown-in-minutes: 5
blacklisted-worlds:
  - world_number_1
  - world_number_2

shop-gui:
  enabled: true
  rows: 4
  aliases:
    - shop
    - shops
  filler-item: GRAY_STAINED_GLASS_PANE
  category-gui:
    buttons:
      scroll-down:
        display: <gray>Scroll Down
        lore:
          - <gray>Click to scroll down...
        item: RED_STAINED_GLASS_PANE
      scroll-up:
        display: <gray>Scroll Up
        lore:
          - <gray>Click to scroll up...
        item: GREEN_STAINED_GLASS_PANE
  mode-gui:
    title: Shop Mode
    rows: 1
    buttons:
      buy:
        display: <gradient:#30ff42:#ff8000><bold>Buy</bold></gradient>
        lore:
          - <gray>Click to display all Buy Shops...
        slot: 3
        item: EMERALD
      sell:
        display: <red><bold>Sell
        lore:
          - <gray>Click to display all Sell Shops...
        slot: 5
        item: GOLD_INGOT
  categories:
    building_blocks:
      display: <blue>Blocks</blue>
      lore:
        - <gray>Click to view Blocks shops...</gray>
      slot: 10
      display-item: GRASS_BLOCK
      items:
        - GRASS_BLOCK
        - STONE
        - GRANITE
        - POLISHED_GRANITE
        - DIORITE
        - POLISHED_DIORITE
        - ANDESITE
        - POLISHED_ANDESITE
        - GRASS_BLOCK
        - DIRT
        - COARSE_DIRT
        - PODZOL
        - COBBLESTONE
        - OAK_PLANKS
        - SPRUCE_PLANKS
        - BIRCH_PLANKS
        - JUNGLE_PLANKS
        - ACACIA_PLANKS
        - DARK_OAK_PLANKS
        - OAK_LOG
        - SPRUCE_LOG
        - BIRCH_LOG
        - JUNGLE_LOG
        - ACACIA_LOG
        - DARK_OAK_LOG
        - STRIPPED_OAK_LOG
        - STRIPPED_SPRUCE_LOG
        - STRIPPED_BIRCH_LOG
        - STRIPPED_JUNGLE_LOG
        - STRIPPED_ACACIA_LOG
        - STRIPPED_DARK_OAK_LOG
        - STRIPPED_OAK_WOOD
        - STRIPPED_SPRUCE_WOOD
        - STRIPPED_BIRCH_WOOD
        - STRIPPED_JUNGLE_WOOD
        - STRIPPED_ACACIA_WOOD
        - STRIPPED_DARK_OAK_WOOD
        - OAK_WOOD
        - SPRUCE_WOOD
        - BIRCH_WOOD
        - JUNGLE_WOOD
        - ACACIA_WOOD
        - DARK_OAK_WOOD
        - OAK_LEAVES
        - SPRUCE_LEAVES
        - BIRCH_LEAVES
        - JUNGLE_LEAVES
        - ACACIA_LEAVES
        - DARK_OAK_LEAVES
        - SPONGE
        - WET_SPONGE
        - GLASS
        - LAPIS_ORE
        - LAPIS_BLOCK
        - SANDSTONE
        - CHISELED_SANDSTONE
        - CUT_SANDSTONE
        - NOTE_BLOCK
        - POWERED_RAIL
        - DETECTOR_RAIL
        - STICKY_PISTON
        - COBWEB
        - GRASS
        - FERN
        - DEAD_BUSH
        - SEAGRASS
        - SEA_PICKLE
        - PISTON
        - WHITE_WOOL
        - ORANGE_WOOL
        - MAGENTA_WOOL
        - LIGHT_BLUE_WOOL
        - YELLOW_WOOL
        - LIME_WOOL
        - PINK_WOOL
        - GRAY_WOOL
        - LIGHT_GRAY_WOOL
        - CYAN_WOOL
        - PURPLE_WOOL
        - BLUE_WOOL
        - BROWN_WOOL
        - GREEN_WOOL
        - RED_WOOL
        - BLACK_WOOL
        - DANDELION
        - POPPY
        - BLUE_ORCHID
        - ALLIUM
        - AZURE_BLUET
        - RED_TULIP
        - ORANGE_TULIP
        - WHITE_TULIP
        - PINK_TULIP
        - OXEYE_DAISY
        - CORNFLOWER
        - LILY_OF_THE_VALLEY
        - WITHER_ROSE
        - BROWN_MUSHROOM
        - RED_MUSHROOM
        - GOLD_BLOCK
        - IRON_BLOCK
        - OAK_SLAB
        - SPRUCE_SLAB
        - BIRCH_SLAB
        - JUNGLE_SLAB
        - ACACIA_SLAB
        - DARK_OAK_SLAB
        - STONE_SLAB
        - SMOOTH_STONE_SLAB
        - SANDSTONE_SLAB
        - CUT_SANDSTONE_SLAB
        - PETRIFIED_OAK_SLAB
        - COBBLESTONE_SLAB
        - BRICK_SLAB
        - STONE_BRICK_SLAB
        - NETHER_BRICK_SLAB
        - QUARTZ_SLAB
        - RED_SANDSTONE_SLAB
        - CUT_RED_SANDSTONE_SLAB
        - PURPUR_SLAB
        - PRISMARINE_SLAB
        - PRISMARINE_BRICK_SLAB
        - DARK_PRISMARINE_SLAB
        - SMOOTH_QUARTZ
        - SMOOTH_RED_SANDSTONE
        - SMOOTH_SANDSTONE
        - SMOOTH_STONE
        - BRICKS
        - TNT
        - BOOKSHELF
        - MOSSY_COBBLESTONE
        - OBSIDIAN
        - TORCH
        - END_ROD
        - CHORUS_PLANT
        - CHORUS_FLOWER
        - PURPUR_BLOCK
        - PURPUR_PILLAR
        - PURPUR_STAIRS
        - SPAWNER
        - OAK_STAIRS
        - CHEST
        - DIAMOND_ORE
        - DIAMOND_BLOCK
        - CRAFTING_TABLE
        - FARMLAND
        - FURNACE
        - LADDER
        - RAIL
        - COBBLESTONE_STAIRS
        - LEVER
        - STONE_PRESSURE_PLATE
        - OAK_PRESSURE_PLATE
        - SPRUCE_PRESSURE_PLATE
        - BIRCH_PRESSURE_PLATE
        - JUNGLE_PRESSURE_PLATE
        - ACACIA_PRESSURE_PLATE
        - DARK_OAK_PRESSURE_PLATE
        - REDSTONE_ORE
        - REDSTONE_TORCH
        - SNOW
        - ICE
        - SNOW_BLOCK
        - CACTUS
        - CLAY
        - JUKEBOX
        - OAK_FENCE
        - SPRUCE_FENCE
        - BIRCH_FENCE
        - JUNGLE_FENCE
        - ACACIA_FENCE
        - DARK_OAK_FENCE
        - PUMPKIN
        - NETHERRACK
        - SOUL_SAND
        - GLOWSTONE
        - JACK_O_LANTERN
        - OAK_TRAPDOOR
        - SPRUCE_TRAPDOOR
        - BIRCH_TRAPDOOR
        - JUNGLE_TRAPDOOR
        - ACACIA_TRAPDOOR
        - DARK_OAK_TRAPDOOR
        - INFESTED_STONE
        - INFESTED_COBBLESTONE
        - INFESTED_STONE_BRICKS
        - INFESTED_MOSSY_STONE_BRICKS
        - INFESTED_CRACKED_STONE_BRICKS
        - INFESTED_CHISELED_STONE_BRICKS
        - STONE_BRICKS
        - MOSSY_STONE_BRICKS
        - CRACKED_STONE_BRICKS
        - CHISELED_STONE_BRICKS
        - BROWN_MUSHROOM_BLOCK
        - RED_MUSHROOM_BLOCK
        - MUSHROOM_STEM
        - IRON_BARS
        - GLASS_PANE
        - MELON
        - VINE
        - OAK_FENCE_GATE
        - SPRUCE_FENCE_GATE
        - BIRCH_FENCE_GATE
        - JUNGLE_FENCE_GATE
        - ACACIA_FENCE_GATE
        - DARK_OAK_FENCE_GATE
        - BRICK_STAIRS
        - STONE_BRICK_STAIRS
        - MYCELIUM
        - LILY_PAD
        - NETHER_BRICKS
        - NETHER_BRICK_FENCE
        - NETHER_BRICK_STAIRS
        - ENCHANTING_TABLE
        - END_PORTAL_FRAME
        - END_STONE
        - END_STONE_BRICKS
        - DRAGON_EGG
        - REDSTONE_LAMP
        - SANDSTONE_STAIRS
        - EMERALD_ORE
        - ENDER_CHEST
        - TRIPWIRE_HOOK
        - EMERALD_BLOCK
        - SPRUCE_STAIRS
        - BIRCH_STAIRS
        - JUNGLE_STAIRS
        - BEACON
        - COBBLESTONE_WALL
        - MOSSY_COBBLESTONE_WALL
        - BRICK_WALL
        - PRISMARINE_WALL
        - RED_SANDSTONE_WALL
        - MOSSY_STONE_BRICK_WALL
        - GRANITE_WALL
        - STONE_BRICK_WALL
        - NETHER_BRICK_WALL
        - ANDESITE_WALL
        - RED_NETHER_BRICK_WALL
        - SANDSTONE_WALL
        - END_STONE_BRICK_WALL
        - DIORITE_WALL
        - OAK_BUTTON
        - SPRUCE_BUTTON
        - BIRCH_BUTTON
        - JUNGLE_BUTTON
        - ACACIA_BUTTON
        - DARK_OAK_BUTTON
        - ANVIL
        - CHIPPED_ANVIL
        - DAMAGED_ANVIL
        - TRAPPED_CHEST
        - LIGHT_WEIGHTED_PRESSURE_PLATE
        - HEAVY_WEIGHTED_PRESSURE_PLATE
    tools_weapons:
      display: <dark_gray>Tools & Weapons</dark_gray>
      lore:
        - <gray>Click to view Tools & Weapons shops...</gray>
      slot: 12
      display-item: IRON_SWORD
      items:
        - NETHERITE_SWORD
        - NETHERITE_SHOVEL
        - NETHERITE_PICKAXE
        - NETHERITE_AXE
        - NETHERITE_HOE
        - DIAMOND_SWORD
        - DIAMOND_SHOVEL
        - DIAMOND_PICKAXE
        - DIAMOND_AXE
        - DIAMOND_HOE
        - STONE_SWORD
        - STONE_SHOVEL
        - STONE_PICKAXE
        - STONE_AXE
        - STONE_HOE
        - GOLDEN_SWORD
        - GOLDEN_SHOVEL
        - GOLDEN_PICKAXE
        - GOLDEN_AXE
        - GOLDEN_HOE
        - WOODEN_SWORD
        - WOODEN_SHOVEL
        - WOODEN_PICKAXE
        - WOODEN_AXE
        - WOODEN_HOE
        - IRON_SWORD
        - IRON_SHOVEL
        - IRON_PICKAXE
        - IRON_AXE
        - IRON_HOE
        - BOW
        - ARROW
        - TRIDENT
    armor:
      display: <gold>Armor</gold>
      lore:
        - <gray>Click to view Armor shops...</gray>
      slot: 14
      display-item: IRON_CHESTPLATE
      items:
        - SHIELD
        - NETHERITE_HELMET
        - NETHERITE_CHESTPLATE
        - NETHERITE_LEGGINGS
        - NETHERITE_BOOTS
        - DIAMOND_HELMET
        - DIAMOND_CHESTPLATE
        - DIAMOND_LEGGINGS
        - DIAMOND_BOOTS
        - IRON_HELMET
        - IRON_CHESTPLATE
        - IRON_LEGGINGS
        - IRON_BOOTS
        - GOLDEN_HELMET
        - GOLDEN_CHESTPLATE
        - GOLDEN_LEGGINGS
        - GOLDEN_BOOTS
        - CHAINMAIL_HELMET
        - CHAINMAIL_CHESTPLATE
        - CHAINMAIL_LEGGINGS
        - CHAINMAIL_BOOTS
        - LEATHER_HELMET
        - LEATHER_CHESTPLATE
        - LEATHER_LEGGINGS
        - LEATHER_BOOTS
        - TURTLE_HELMET
    food_cooking:
      display: <yellow>Food & Cooking</yellow>
      lore:
        - <gray>Click to view Food & Cooking shops...</gray>
      slot: 16
      display-item: BREAD
      items:
        - APPLE
        - BREAD
        - PORKCHOP
        - COOKED_PORKCHOP
        - GOLDEN_APPLE
        - COOKED_SALMON
    redstone:
      display: <red>Redstone</red>
      lore:
        - <gray>Click to view Redstone shops...</gray>
      slot: 18
      display-item: REDSTONE
      items:
        - REDSTONE
        - REDSTONE_TORCH
        - LEVER
        - PISTON
        - STICKY_PISTON
        - NOTE_BLOCK
    miscellaneous:
      display: <pink>Miscellaneous</pink>
      lore:
        - <gray>Click to view Miscellaneous items...</gray>
      slot: 20
      display-item: LAVA_BUCKET
      items:
        - LAVA_BUCKET
        - WATER_BUCKET
        - EGG
        - SNOWBALL
        - PAPER
        - BOOK
        - SLIME_BALL
    potions_brewing:
      display: <dark_purple>Potions & Brewing</dark_purple>
      lore:
        - <gray>Click to view Potions & Brewing shops...</gray>
      slot: 22
      display-item: POTION
      items:
        - POTION
        - SPLASH_POTION
        - LINGERING_POTION
        - BREWING_STAND
        - BLAZE_POWDER
        - NETHER_WART
        - FERMENTED_SPIDER_EYE
        - GLISTERING_MELON_SLICE
    enchanted_books:
      display: <aqua>Enchanted Books</aqua>
      lore:
        - <gray>Click to view Enchanted Books shops...</gray>
      slot: 24
      display-item: ENCHANTED_BOOK
      items:
        - ENCHANTED_BOOK
        - BOOKSHELF
        - ANVIL
        - ENCHANTING_TABLE
        - EXPERIENCE_BOTTLE
    nature_farming:
      display: <green>Nature & Farming</green>
      lore:
        - <gray>Click to view Nature & Farming shops...</gray>
      slot: 26
      display-item: WHEAT_SEEDS
      items:
        - WHEAT_SEEDS
        - CARROT
        - POTATO
        - BEETROOT_SEEDS
        - PUMPKIN_SEEDS
        - MELON_SEEDS
        - BONE_MEAL
        - SUGAR_CANE
        - CACTUS
debug-mode: false
config-version: 12

